kind: pipeline
type: docker
name: Build

steps:
- name: Docker Build
  image: plugins/docker
  settings:
    username: chaikair
    password: 389609066
    repo: chaikair/ttyd-arm64
    tags:
    - latest
    - main
